export const MENTOR_LINES = [
  'Ah! So you must be the new bartender! Mary, was it?',
  "I'm Carmilla, here to show you the ropes! Good to meet you!",
  'First thing you gotta know: \n\nEvery customer has their likes and dislikes.',
  "For example, I like fish blood!\n\nYeah it's a bit weird, but I love the fishy taste.",
  'In fact, I love it so much I wear blue!', // Play a little thingy here
  'Good thing is, our customers also wear the color of the blood they like!\n\nSo pay close attention to their clothing.',
  "If they ask for something 'delicious' or 'flavorful', or 'yummy'...\n\nYou can bet the blood they want will match the color of their shirt!",
  'Nifty, eh?',
  "Anyways, I don't like reptilian blood very much.\n\nIt's actually poisonous to me because I'm allergic!",
  'Lucky for you, the color of my eyes says that all.\n\nFun fact, all vampires have this trait.',
  'But sometimes, I do like some reptilian blood for an added kick.\n\nKind of like really spicy food!',
  'Be aware! Some people are real masochists and love drinking poison!',
  "But not to worry, since they'll let you know.\n\nThey'll usually say they want something 'dangerous' or 'risky', or something like that..",
  "Be careful with poisons though! Too much and you'll literally kill them!\n\nAnd we don't want that, especially on your first night..",
  'Which brings me to the next thing you gotta know: \n\nHow much to pour!',
  'Listen closely to what the customers say.',
  'For example, if I say I want a "little" of something, just give me two pours. (Or a quarter of a glass)',
  "I've put useful keywords to look out for in that handy dandy guidebook on the right!",
  'It should tell you how much to pour (Usually a quarter, half, three quarters, or full!)',
  "Oh, and you need to pour until the glass is full before you can serve.\n\nOur customers really wanna get their money's worth.",
  'Finally, the last thing to know is about speediness and your reputation!',
  'Our customers are pretty impatient!\n\nSo make sure to keep an eye on that Timer up on the right.\n\nIf it hits zero, customers might just bail on you!',
  "But don't worry if you need to check the guidebook. Our customers will wait. \n\nAfter all, a messed up order might cost them their life!",
  "Next, pay attention to your reputation, or Rep.\n\n It'll increase or decrease based on how well you mix drinks.",
  'Mix em good, and the number goes up!\n\nMix em bad, and it goes down...\n\nSimple enough.',
  "I put in a good word about you, so you should have some street cred to start.\n\nBut don't let it go to zero or you might just get canned!",
  "Alright, I think that's it! Let's try a sample order. Hmm..let's see..",
]
